apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: nodejs
  namespace: {{ .Release.Namespace }}
spec:
  exporter:
    endpoint: {{ .Values.tempoEndpoint }}
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  nodejs:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: {{ .Values.tempoEndpoint }}
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
